[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
version = "auto"
included-patches = "client-spoof disable-auto-captions disable-shorts-on-startup disable-zoom-haptics external-downloads hdr-auto-brightness hide-ads hide-cast-button hide-floating-microphone-button hide-watch-in-vr hide-watermark minimized-playback old-quality-layout premium-heading remember-video-quality return-youtube-dislike seekbar-tapping sponsorblock swipe-controls theme vanced-microg-support video-ads"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
version = "auto"

